CREATE DATABASE Profe;

CREATE TABLE A(
	Id_A int PRIMARY KEY,
	Col_A_FK_B int 
);

CONSTRAINT Id_A FOREIGN KEY (B_FK_A) REFERENCES A (Id_A)

CONSTRAINT Id_A FOREIGN KEY (FK_A) REFERENCES A (Id_A)

CREATE TABLE B(
	Col_B_FK_A int ,
	Id_B int PRIMARY KEY
);

CONSTRAINT Id_B FOREIGN KEY (A_FK_B) REFERENCES B (Id_B)

CONSTRAINT Id_B FOREIGN KEY (FK_B) REFERENCES B (Id_B)

CREATE TABLE FK_A_B(
	Col_FK_A int PRIMARY KEY,
	Col_FK_B int PRIMARY KEY
);

