CREATE DATABASE Prueba;

DROP TABLE IF EXISTS Clase 1;
CREATE TABLE Clase 1;

DROP TABLE IF EXISTS Clase 2;
CREATE TABLE Clase 2;

DROP TABLE IF EXISTS clase hijo;
CREATE TABLE clase hijo;

DROP TABLE IF EXISTS CAso;
CREATE TABLE CAso;
